server:
  port: 8080
spring:
  application:
    name: tribe-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.197.195:3306/tribe?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: cttao
    password: 123456

